config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :authors
  
  root 'home#index'

  

  

end

app/models/application_record.rb
# By default all new Rails 5 applications will have application_record.rb.
# If you are migrating from Rails 4, then simply create app/models/application_record.rb
# as shown below and change all models to inherit from ApplicationRecord instead of ActiveRecord::Base.
# https://stackoverflow.com/questions/41387706/uninitialized-constant-applicationrecord-error#41388844
# https://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= form_with scope: :author, url: authors_path, local: true do |form| %>
  
    <p>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %>
    </p>
    
    <p>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %>
    </p>
  
    <p>
      <%= form.label :homepage %><br>
      <%= form.text_field :homepage %>
    </p>
    
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

Paper Management System

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SWT II Intro Exercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>